ALTER TABLE source_scenes
    ADD COLUMN IF NOT EXISTS dates JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS duration INTEGER,
    ADD COLUMN IF NOT EXISTS director TEXT,
    ADD COLUMN IF NOT EXISTS code TEXT,
    ADD COLUMN IF NOT EXISTS studio_endpoint TEXT,
    ADD COLUMN IF NOT EXISTS studio_stash_id TEXT;

ALTER TABLE source_performers
    ADD COLUMN IF NOT EXISTS aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS gender TEXT,
    ADD COLUMN IF NOT EXISTS country TEXT,
    ADD COLUMN IF NOT EXISTS ethnicity TEXT,
    ADD COLUMN IF NOT EXISTS eye_color TEXT,
    ADD COLUMN IF NOT EXISTS hair_color TEXT,
    ADD COLUMN IF NOT EXISTS measurements TEXT,
    ADD COLUMN IF NOT EXISTS career_years JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS remote_images JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE source_scene_performers
    ADD COLUMN IF NOT EXISTS appearance_order INTEGER NOT NULL DEFAULT 1;

ALTER TABLE source_scene_tags
    ADD COLUMN IF NOT EXISTS tag_order INTEGER NOT NULL DEFAULT 1;
